services:
  endpaper:
    image: fklement/endpaper:latest@sha256:83001f4acbd875e73bc1b21160a15c36d607ebb4eb4dc12feed9f3ee6822bb29
    container_name: endpaper
    ports:
      - "8000:8000"     # change left side to any free host port e.g. 8123:8000
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=REPLACE_WITH_A_LONG_RANDOM_STRING
      - DATABASE_URL=sqlite:///./data/library.db
    restart: unless-stopped
