services:
  endpaper:
    image: fklement/endpaper:latest@sha256:82d8055af81c3a6e77be9e3bb7b8fad096b6d2516200ef794b8a8e00aa27dd09
    container_name: endpaper
    ports:
      - "8000:8000"     # change left side to any free host port e.g. 8123:8000
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=REPLACE_WITH_A_LONG_RANDOM_STRING
      - DATABASE_URL=sqlite:///./data/library.db
    restart: unless-stopped
