services:
  endpaper:
    image: fklement/endpaper:latest@sha256:663a3e953a9ac25029ac5b05878d805fa60aad566191b639b920efdf058e096b
    container_name: endpaper
    ports:
      - "8000:8000"     # change left side to any free host port e.g. 8123:8000
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=REPLACE_WITH_A_LONG_RANDOM_STRING
      - DATABASE_URL=sqlite:///./data/library.db
    restart: unless-stopped
