"""book ownership status

Revision ID: a7feb2db74ac
Revises: ce4ea3c0a86e
Create Date: 2026-08-18 18:46:38.952458

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7feb2db74ac"
down_revision: str | Sequence[str] | None = "ce4ea3c0a86e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ownership", sa.String(length=20), server_default="owned", nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_books_ownership"), ["ownership"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_books_ownership"))
        batch_op.drop_column("ownership")

    # ### end Alembic commands ###
