"""settings table, auth source, enrichment fields

Revision ID: ce4ea3c0a86e
Revises: 6ac5f778dadb
Create Date: 2026-08-18 18:02:27.879776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce4ea3c0a86e"
down_revision: str | Sequence[str] | None = "6ac5f778dadb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("language", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("categories", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("google_books_id", sa.String(length=50), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("auth_source", sa.String(length=20), server_default="local", nullable=False)
        )
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.drop_column("auth_source")

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_column("google_books_id")
        batch_op.drop_column("categories")
        batch_op.drop_column("language")
        batch_op.drop_column("page_count")

    op.drop_table("settings")
    # ### end Alembic commands ###
